name: Docker

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: docker build --tag green-compute-scheduler:${{ github.sha }} .
